Gem::Specification.new do |s|
  s.name = %q{openfoundry_dependent_gems}
  s.version = "0.1"
  s.date = %q{2008-01-24}
  s.summary = %q{OpenFoundry dependent gems.}
  s.email = %q{contact@openfoundry.org}
  s.homepage = %q{http://www.openfoundry.org}
  s.rubyforge_project = %q{openfoundry}
  s.description = %q{OpenFoundry dependent gems.}
#  s.default_executable = %q{rails}
  s.authors = ["OpenFoundry team"]
  s.files = []
  s.rdoc_options = ["--exclude", "."]
#  s.executables = ["rails"]

#luors@test01:~$ gem list | ruby -ne 'puts "  s.add_dependency(%q<#{$1}>, [\"= #{$2}\"])" if /^(\S+).*\((.*?)\)/'

#  s.add_dependency(%q<actionmailer>, ["= 2.0.2"])
#  s.add_dependency(%q<actionpack>, ["= 2.0.2"])
#  s.add_dependency(%q<actionwebservice>, ["= 1.2.6"])
#  s.add_dependency(%q<activerecord>, ["= 2.0.2"])
#  s.add_dependency(%q<activeresource>, ["= 2.0.2"])
#  s.add_dependency(%q<activesupport>, ["= 2.0.2"])
  s.add_dependency(%q<acts_as_ferret>, ["= 0.4.3"])
  s.add_dependency(%q<acts_as_taggable>, ["= 2.0.2"])
#  s.add_dependency(%q<ar_fixtures>, ["= 0.0.4"])
  s.add_dependency(%q<cgi_multipart_eof_fix>, ["= 2.5.0"])
#  s.add_dependency(%q<daemons>, ["= 1.0.9"])
#  s.add_dependency(%q<deprecated>, ["= 2.0.0"])
#  s.add_dependency(%q<fastthread>, ["= 1.0.1"])
  s.add_dependency(%q<ferret>, ["= 0.11.6"])
#  s.add_dependency(%q<flexmock>, ["= 0.8.0"])
#  s.add_dependency(%q<fxri>, ["= 0.3.6"])
#  s.add_dependency(%q<fxruby>, ["= 1.6.13"])
#  s.add_dependency(%q<gem_plugin>, ["= 0.2.3"])
#  s.add_dependency(%q<gemsonrails>, ["= 0.7.1"])
  s.add_dependency(%q<gettext>, ["= 1.10.0"])
#  s.add_dependency(%q<highline>, ["= 1.4.0"])
#  s.add_dependency(%q<hoe>, ["= 1.4.0"])
  s.add_dependency(%q<json>, ["= 1.1.2"])
  s.add_dependency(%q<mongrel>, ["= 1.1.3"])
#  s.add_dependency(%q<needle>, ["= 1.3.0"])
#  s.add_dependency(%q<net-sftp>, ["= 1.1.0"])
#  s.add_dependency(%q<net-ssh>, ["= 1.1.2"])
  s.add_dependency(%q<rails>, ["= 2.0.2"])
  s.add_dependency(%q<rake>, ["= 0.8.1"])
#  s.add_dependency(%q<rcov>, ["= 0.8.1.2.0"])
  s.add_dependency(%q<rmagick>, ["= 1.15.12"])
  s.add_dependency(%q<rspec>, ["= 1.1.2"])
#  s.add_dependency(%q<ruby-debug>, ["= 0.10.0"])
#  s.add_dependency(%q<ruby-debug-base>, ["= 0.10.0, 0.9.3"])
#  s.add_dependency(%q<ruby-debug-ide>, ["= 0.1.9"])
#  s.add_dependency(%q<ruby-growl>, ["= 1.0.1"])
#  s.add_dependency(%q<rubyforge>, ["= 0.4.4"])
  s.add_dependency(%q<rubygems-update>, ["= 1.0.1"])
#  s.add_dependency(%q<rudebug>, ["= 0.3.2"])
#  s.add_dependency(%q<salted_login_generator>, ["= 1.1.1"])
#  s.add_dependency(%q<sources>, ["= 0.0.1"])
#  s.add_dependency(%q<syntax>, ["= 1.0.0"])
  s.add_dependency(%q<tzinfo>, ["= 0.3.6"])
#  s.add_dependency(%q<uuidtools>, ["= 1.0.3, 1.0.2"])
#  s.add_dependency(%q<ZenTest>, ["= 3.8.0, 3.7.1, 3.6.1"])
end
